// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7AhZ2Pu3U-RadxO8G23YL_37pYDTcvDQ',
    appId: '1:511977469552:web:2cfc45bb32e22966c026b5',
    messagingSenderId: '511977469552',
    projectId: 'login-12b4b',
    authDomain: 'login-12b4b.firebaseapp.com',
    storageBucket: 'login-12b4b.firebasestorage.app',
    measurementId: 'G-TZGE1XPTZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMaGEgjpGAx0wAwX8w-N6gD3YPOBlk5XI',
    appId: '1:511977469552:android:101ad42759a2016dc026b5',
    messagingSenderId: '511977469552',
    projectId: 'login-12b4b',
    storageBucket: 'login-12b4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7DVe1f1rAKCkZO0hwvcTh-yWhBBIljgk',
    appId: '1:511977469552:ios:c331ea9bedfc17b2c026b5',
    messagingSenderId: '511977469552',
    projectId: 'login-12b4b',
    storageBucket: 'login-12b4b.firebasestorage.app',
    iosBundleId: 'com.example.appChatFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7DVe1f1rAKCkZO0hwvcTh-yWhBBIljgk',
    appId: '1:511977469552:ios:c331ea9bedfc17b2c026b5',
    messagingSenderId: '511977469552',
    projectId: 'login-12b4b',
    storageBucket: 'login-12b4b.firebasestorage.app',
    iosBundleId: 'com.example.appChatFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7AhZ2Pu3U-RadxO8G23YL_37pYDTcvDQ',
    appId: '1:511977469552:web:55b2995dd75440f0c026b5',
    messagingSenderId: '511977469552',
    projectId: 'login-12b4b',
    authDomain: 'login-12b4b.firebaseapp.com',
    storageBucket: 'login-12b4b.firebasestorage.app',
    measurementId: 'G-35136BDH5Z',
  );
}
